name: Label PR for patch upgrade
on:
  pull_request_target:
    type:
      - opened

jobs:
  tag-pull-request-with-patch-upgrade-label:
    runs-on: ubuntu-latest
    if: |
      ${{
          !contains(github.event.pull_request.labels.*.name, 'major-version') 
          && !contains(github.event.pull_request.labels.*.name, 'minor-version') 
          && !contains(github.event.pull_request.labels.*.name, 'patch-version') 
      }}
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.NORI_ESLINT_PAT }}
          number: ${{ github.event.pull_request.number }}
          labels: patch-version