name: package auto-updater
on:
  pull_request_target:
    types:
      - labeled
      - created

jobs:
  package-auto-updater:
    if: ${{ github.event.label.name == 'upgrade-patch-version' }}
    runs-on: ubuntu-latest # check if this is best, or a yarn image
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.issue.pull_request.head.ref}}
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: '0'
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
        # TODO implement the below command against either ALL or against UPDATED packages
      - run: |
          # TODO - compare package versions to master
          # if master's are newer, increment them by one patch number

          yarn version --patch --no-git-tag-version;
          yarn workspace @nori-dot-com/cspell version --patch --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/errors version --patch --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/eslint-config-nori version --patch --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/ggit version --patch --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/math version --patch --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/project version --patch --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/quantification version --patch --no-git-tag-version --no-commit-hooks;
      - run: |
          git config --global user.email "github@nori.com";
          git config --global user.name "Github";
          git add .;
          git diff --staged --quiet || git commit -m "Upgrading package versions";
          git push;
      - uses: actions-ecosystem/remove-add-labels@v1
        with:
          number: ${{ github.event.number }}
          labels: upgrade-patch-version
