name: Auto-Update package versions
on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - created

jobs:
  remove-package-upgrade-label:
    if: ${{ github.event.label }} # If PR was triggered with label
    runs-on: ubuntu-latest 
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          number: ${{ github.event.number }}
          labels: upgrade-version

  package-auto-updater:
    # If this event is for a PR creation, or has a specific label
    if: |
      ${{ 
        !github.event.label 
        || github.event.label.name == 'major' 
        || github.event.label.name == 'minor' 
        ||  (
              github.event.label.name == 'upgrade-version' 
              && github.event.action == 'labeled'
            )
      }}
    runs-on: ubuntu-latest
    concurrency: auto-updater-${{ github.event.pull_request.head.ref }}
    steps:
      - name: checkout source
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: '0'
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: reset package versions to the base
        run: |
          git config --global user.email "github@nori.com";
          git config --global user.name "Github";

          git diff --staged --quiet || git commit -m "Upgrading package versions";
          git fetch origin ${{ github.event.pull_request.base.ref }};
          git checkout origin/${{ github.event.pull_request.base.ref }} -- package.json;

          BASE_VERSION=$(
            cat package.json \
              | grep "^\s*\"version\": \"" \
              | awk '{ print $2 }' \
              | sed 's|[",]||g'
            );

          git reset --hard HEAD;

          yarn version --new-version $BASE_VERSION --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/cspell version --new-version $BASE_VERSION --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/errors version --new-version $BASE_VERSION --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/eslint-config-nori version --new-version $BASE_VERSION --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/ggit version --new-version $BASE_VERSION --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/math version --new-version $BASE_VERSION --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/project version --new-version $BASE_VERSION --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/quantification version --new-version $BASE_VERSION --no-git-tag-version --no-commit-hooks;

          git add .;
          git diff --staged --quiet || git commit -m "Reset package versions to match base";
      - name: increment package versions
        run: |

          if ${{ contains(github.event.pull_request.labels.*.name, 'major') }}; then
            VERSION_UPGRADE_TYPE="--major";
          elif ${{ contains(github.event.pull_request.labels.*.name, 'minor') }}; then
            VERSION_UPGRADE_TYPE="--minor";
          else
            VERSION_UPGRADE_TYPE="--patch";
          fi

          yarn version $VERSION_UPGRADE_TYPE --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/cspell version $VERSION_UPGRADE_TYPE --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/errors version $VERSION_UPGRADE_TYPE --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/eslint-config-nori version $VERSION_UPGRADE_TYPE --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/ggit version $VERSION_UPGRADE_TYPE --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/math version $VERSION_UPGRADE_TYPE --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/project version $VERSION_UPGRADE_TYPE --no-git-tag-version --no-commit-hooks;
          yarn workspace @nori-dot-com/quantification version $VERSION_UPGRADE_TYPE --no-git-tag-version --no-commit-hooks;

          git add .;
          git diff --staged --quiet || git commit -m "Upgrading package versions";
      - name: push updates to pr branch
        run: git push;
