name: package auto-update trigger
on:
  pull_request_target:
    types:
      - opened
jobs:
  package-auto-updater-trigger:
    # if: github.event.comment.user.email == 'github@nori.com' && github.event.comment.body == 'Bumping package versions'
    runs-on: ubuntu-latest # check if this is best, or a yarn image
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          pr_number: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.NORI_ESLINT_PAT }}
          create_if_not_exists: true
          message: |
            Bump package versions